### ISSUE TITLE
Unable to build 1.4 LTS

### ISSUE THREAD

**Issue by BurlyLuo** [onedr0p/vyos-build#123]
follow ```https://docs.vyos.io/en/latest/contributing/build-vyos.html```
and checkout to the epa version:
```
root@d05b48444eb8:/vyos# git status
HEAD detached at 1.4.0-epa1
nothing to commit, working tree clean
root@d05b48444eb8:/vyos# 
```
but get the below error:
```
208  docker run -td  --privileged -v $(pwd):/vyos -w /vyos vyos/vyos-build:sagitta bash

Need to get 45.9 kB of archives.
After this operation, 158 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bookworm/main amd64 acpid amd64 1:2.0.33-2+b1 [45.9 kB]
Fetched 45.9 kB in 0s (129 kB/s)
Selecting previously unselected package acpid.
(Reading database ... 82673 files and directories currently installed.)
Preparing to unpack .../acpid_1%3a2.0.33-2+b1_amd64.deb ...
Unpacking acpid (1:2.0.33-2+b1) ...
Setting up acpid (1:2.0.33-2+b1) ...
Running in chroot, ignoring request.
All runlevel operations denied by policy
invoke-rc.d: policy-rc.d denied execution of start.
Created symlink /etc/systemd/system/sockets.target.wants/acpid.socket → /lib/systemd/system/acpid.socket.
Created symlink /etc/systemd/system/paths.target.wants/acpid.path → /lib/systemd/system/acpid.path.
P: Executing hook config/hooks/live/15-sources_list.chroot...
P: Executing hook config/hooks/live/16-fuse.chroot...
P: Executing hook config/hooks/live/17-gen_initramfs.chroot...
I: Create initramfs if it does not exist.
E: there is more than one kernel image file installed!
E: please make sure that kernel_version in data/defaults.toml is up to date
E: if your repository is up to date, then there is a bug
I: Executing update-initramfs -c -k 6.6.17-amd64-vyos
6.6.19-amd64-vyos
Extra argument '6.6.19-amd64-vyos'


Usage: update-initramfs {-c|-d|-u} [-k version] [-v] [-b directory]

Options:
 -k version     Specify kernel version or 'all'
 -c             Create a new initramfs
 -u             Update an existing initramfs
 -d             Remove an existing initramfs
 -b directory   Set alternate boot directory
 -v             Be verbose

See update-initramfs(8) for further details.

E: config/hooks/live/17-gen_initramfs.chroot failed (exit non-zero). You should check for errors.
```
would you please suggest here, thanks a lot. 

i checked your iso about the 1.4epa, and convert to the container image. but when run out for a container and save the configuration, but get ```vyos  unable to resolve host leaf0: System error``` follow this link: ```https://docs.vyos.io/en/latest/installation/virtual/docker.html```

**Comment by onedr0p** [comment]
I would bring this up in the vyos forums maybe? I am not sure what to say.

**Comment by onedr0p** [comment]
I found your post in their forums

https://forum.vyos.io/t/build-issue-for-1-4-0-epa/13943

**Comment by onedr0p** [comment]
This is broken because Vyos does not (to my knowledge) publish a APT repo for LTS, packages will always be pulled from the rolling APT repo which will cause breakage in the LTS builds.

As far as I can see things, it is not possible to build Vyos LTS releases until they support methods for us to do so which is highly unlikely given their stance on not building LTS for the public.

Vyos ✌🏼  ... Whyos 🤷🏼‍♂️  ... Cryos 😢

**Comment by BurlyLuo** [comment]
yes, let discuss at forums.

**Comment by Himurae** [comment]
we understand we are getting premium software for free a simple edit in the documentation would suffice.......

**Comment by onedr0p** [comment]
I have opened a PR here

https://github.com/vyos/vyos-documentation/pull/1324
