### ISSUE TITLE
1.3 LTS?

### ISSUE THREAD

**Issue by RSully** [onedr0p/vyos-build#128]
Would it be possible to add the latest 1.3.x image to this project and have those LTS images built as they are released? My understanding is 1.3 will get bug fixes for a while still.

**Comment by onedr0p** [comment]
It seems possible but not something I am looking to maintain. I want to keep it simple and build current LTS (1.4) and whatever is the latest rolling (1.5).

Once 1.5 is the current LTS I will be dropping 1.4 and focusing on 1.5 LTS and future 1.6. 

Hope that all makes sense and feel free to fork the repo and do you own builds, sorry.
