### ISSUE TITLE
Resource not accessible by integration

### ISSUE THREAD

**Issue by soulwhisper** [onedr0p/vyos-build#129]
![Screenshot_2024-03-25-22-53-23-238_com android chrome-edit](https://github.com/onedr0p/vyos-build/assets/26273512/af802764-3ffe-4fec-be6a-ec5bb0859c52)
Hello, I forked your repo to build my own vyos. However my action stuck at "Decrement build number" with "/repos/soulwhisper/vyos-build: Resource not accessible by integration".

My github app is set with " Read access to Dependabot alerts, actions variables, and metadata" and "Read and write access to actions, administration, checks, code, commit statuses, issues, packages, pull requests, and workflows".

Any suggestion?

**Comment by onedr0p** [comment]
You also need this set

<img width="712" alt="image" src="https://github.com/onedr0p/vyos-build/assets/213795/ce572232-3269-4c7a-a060-9c1a3063b502">
