### ISSUE TITLE
Stop distributing prebuilt VyOS images with the artwork and trademarked name

### ISSUE THREAD

**Issue by dmbaturin** [onedr0p/vyos-build#134]
Here is a gentle reminder that VyOS is a registered trademark and that the artwork is **not** under a license that allows redistribution.

This is the same story as with RedHat and Mozilla: you can build your own CentOS/ScientificLinux/AlmaLinux... or Iceweasel, but you cannot create an impression that the binaries come from RedHat or Mozilla.

If you don't comply, the next step will be a takedown request to GitHub.

**Comment by kashalls** [comment]
@onedr0p 😂

**Comment by buroa** [comment]
> Here is a gentle reminder that VyOS is a registered trademark and that the artwork is **not** under a license that allows redistribution.
> 
> 
> 
> This is the same story as with RedHat and Mozilla: you can build your own CentOS/ScientificLinux/AlmaLinux... or Iceweasel, but you cannot create an impression that the binaries come from RedHat or Mozilla.
> 
> 
> 
> If you don't comply, the next step will be a takedown request to GitHub.

I don't think slamming threats as a simple maintainer of VyOS is the best route here. Don't be a toxic shithead.

**Comment by dmbaturin** [comment]
@buroa Two questions for you:

1. Who's the legal owner of the name and the artwork?
2. Who's resorting to insults?

Thinks about it.

**Comment by kashalls** [comment]
@dmbaturin 

> 1. the artwork

What is this artwork that you are referring to?

**Comment by buroa** [comment]
> @buroa Two questions for you:
> 
> 
> 
> 1. Who's the legal owner of the name and the artwork?
> 
> 2. Who's resorting to insults?
> 
> 
> 
> Thinks about it.

Don't come at people with threats. You picked the right one, and that's me. I'll back up people I support.

**Comment by dmbaturin** [comment]
https://github.com/vyos/vyos-build/blob/current/LICENSE.artwork

**Comment by buroa** [comment]
> https://github.com/vyos/vyos-build/blob/current/LICENSE.artwork

Using an image by itself is not against a trademark. For example, I can use a Facebook logo in my Github repo if I feel the need.

Please consult with a lawyer about your project and don't make assumptions like you own graphics lmao.

**Comment by danmanners** [comment]
![popcorn](https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExM3hmNWgxaTFubzR5cHNjdDRwenI0MnpqY3Y2ZGhkZG1pYmliejc4bSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/2UvAUplPi4ESnKa3W0/giphy.gif)

**Comment by dmbaturin** [comment]
Why do you folks think none of the RHEL binary-compatible clones were named RHEL or used RedHat's artwork? The answer may surprise you.

**Comment by danmanners** [comment]
@onedr0p suggested replacement artwork.
![image](https://github.com/onedr0p/vyos-build/assets/17593824/924b8383-a76f-4e86-b640-ff19f679302f)

**Comment by buroa** [comment]
> Why do you folks think none of the RHEL binary-compatible clones were named RHEL or used RedHat's artwork? The answer may surprise you.

This is where legal advice comes in handy. VyOS offers subscriptions, so there is monetary value here. You would have to then pay a portion to use RHEL artwork.

Welcome to corporate things, buddy.

**Comment by onedr0p** [comment]
I'll rename the repo and update all references to vyos soon.
