### ISSUE TITLE
Rolling workflow seems to produce releases without iso artifact

### ISSUE THREAD

**Issue by samip5** [onedr0p/vyos-build#15]
https://github.com/onedr0p/vyos-build/releases/tag/v1.4-rolling-202310310306

**Comment by onedr0p** [comment]
Yeah this is a known issue when builds fail upstream [this](https://github.com/onedr0p/vyos-build/blob/3ba05cc7de4c6527f56ee569944ce107e837e792/.github/workflows/rolling.yml#L76) was supposed to fix it from happening but doesn't appear like it worked.

**Comment by onedr0p** [comment]
This should be fixed in https://github.com/onedr0p/vyos-build/commit/e6d8aa599982aca9c685e042262c92c55bc0b0bb
