### ISSUE TITLE
Do not release when build is broken

### ISSUE THREAD

**Issue by onedr0p** [onedr0p/vyos-build#9]
Looks like the release happens whether or not an ISO is generated

https://github.com/onedr0p/vyos/releases/tag/v1.4-rolling-202303180306

https://github.com/onedr0p/vyos/actions/runs/4453349884/jobs/7821799855

**Comment by bjw-s** [comment]
This is "fixed" by https://github.com/onedr0p/vyos/commit/3e49181ecc3adc5c9d4e8f97f3ae9ebdee33c344
